castor/castor/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.auth import views as log_views
from common import views as common
from django.contrib.auth import  views as auth_views



urlpatterns = [
    url(r'^', include('users.urls', namespace='users')),
    url(r'^panel', common.panel),
    url(r'^reservas', common.reservas),
    url(r'^recursos/', include('recursos.urls', namespace='recursos')),
    url(r'^admin/', admin.site.urls),
    url(r'^reserva_generica/', include('reserva_generica.urls',namespace='reserva_generica')),
    url(r'^logout/', log_views.logout,name='logout'),
    url(r'^$', common.start),

    url(r'^password_reset/$', auth_views.password_reset, name='password_reset'),
    url(r'^password_reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm, name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.password_reset_complete, name='password_reset_complete'),
]
urlpatterns += staticfiles_urlpatterns()

castor/recursos/urls.py
from django.conf.urls import  url
from . import views
from .views import *

urlpatterns = [
  url(r'^$', views.IndexView.as_view(), name='index'),
  url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),

  url(r'tiporecurso/add/$', views.CrearTipo.as_view(), name='agregar-tiporecurso'),
  url(r'tiporecurso/(?P<pk>[0-9]+)/$', tiporecurso_update, name='actualizar-tiporecurso'),
  url(r'tiporecurso/(?P<pk>[0-9]+)/eliminar/$', views.EliminarTipo.as_view(), name='eliminar-tiporecurso'),

  url(r'^edit/(?P<pk>\d+)$', recurso_update, name='recurso_edit'),
  url(r'^lista/$', recurso_list, name='recurso_list'),
  url(r'^new/$', recurso_create, name='recurso_new'),
  url(r'^delete/(?P<pk>\d+)$', views.recursoDelete.as_view(), name='recurso_delete'),
  url(r'^tiporecurso/recursos/(?P<pk>\d+)$', views.eliminarRecurso.as_view(), name='eliminar_recurso'),
  url(r'^busqueda/recursos/$', recurso_busqueda , name='recurso_busqueda'),
  url(r'^busqueda/tipo_recurso/$', tipo_recurso_busqueda , name='tipo_recurso_busqueda'),
  url(r'^estados/$', recurso_estados, name='recurso_estados'),


]

castor/reserva_generica/urls.py
from django.conf.urls import  url

from .views import *

urlpatterns = [
        url(r'^crear_reserva/$', crear_reserva, name='crear_reserva'),
        url(r'^modificar_reserva/(?P<pk>\d+)/$', Modificar_reserva.as_view() , name='modificar_reserva'),
        url(r'^listar_reserva/$', reserva_list , name='listar_reservas'),
        url(r'^cancelar_reserva/(?P<pk>\d+)$', Cancelar_reserva.as_view(), name='cancelar_reserva'),
]

castor/reservas/urls.py
from django.conf.urls import  url
from . import views

castor/users/urls.py
from django.conf.urls import url
from django.contrib.auth import  views as auth_views
from .views import *


urlpatterns = [
    url(r'^login/$', auth_views.login,  {'template_name': 'users/login.html', }),
    url(r'^register/$', register),
    url(r'^users/$', users_list, name='user_list'),

    url(r'^users/pending/$', users_pending, name='user_pending'),
    url(r'^categoria/(?P<pk>\d+)$', categoria, name='usuario_categoria'),
    url(r'^users/roles/(?P<pk>[0-9]+)/$', administrar_rol_user , name='admin_rol'),
    url(r'^users/edit/(?P<pk>\d+)$', users_update, name='users_edit'),
    url(r'^users/approve/(?P<pk>\d+)$', users_approve, name='users_approve'),
    url(r'^users/new/$', users_create, name='users_new'),
    url(r'^users/delete/(?P<pk>\d+)$', users_delete, name='users_delete'),
    url(r'^users/inicio', inicio, name='users_inicio'),

    url(r'^password_reset/$', auth_views.password_reset, name='password_reset'),
    url(r'^password_reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm, name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.password_reset_complete, name='password_reset_complete'),


    url(r'^login/users/inicio/$', inicio,name='users_inicio'),

    url(r'^roles/$', groups_list, name='groups_list'),
    url(r'^roles/new$', groups_create, name='groups_new'),
    url(r'^roles/edit/(?P<pk>\d+)$', groups_update, name='groups_edit'),
    url(r'^roles/delete/(?P<pk>\d+)$', groups_delete, name='groups_delete'),


]

castor/reserva_generica/models.py
from django.db import models
from users.models import Usuario , User
from recursos.models import TipoRecurso
from django.utils import timezone


#**Class ReservaGenerica**
"""
Crea Formulario de ReservaGenerica
"""
class ReservaGenerica(models.Model):
    usuario = models.ForeignKey(User, null=False)
    tipoRecurso = models.ForeignKey(TipoRecurso, null=False)
    fecha_inicio = models.DateTimeField(blank=False)
    hora_inicio=models.TimeField(default='00:00')
    fecha_fin = models.DateTimeField(blank=False)
    hora_fin = models.TimeField(default='00:00')
    fecha_fin = models.DateTimeField(blank=False)

castor/reservas/models.py
from django.db import models
from users.models import Usuario
from recursos.models import Recurso
from datetime import datetime


#**Class Reserva**
"""
Crea el formulario de Reservas
"""
class Reserva(models.Model):
    usuario = models.ForeignKey(Usuario, null=False)
    recurso = models.ForeignKey(Recurso, null=False)
    # fecha_inicio = models.DateTimeField(null=False, default=datetime.now())
    # fecha_fin = models.DateTimeField(null=False, default=datetime.now())
    verificacion = models.IntegerField(null=True)

castor/reserva_generica/views.py
from django.shortcuts import render, redirect, get_object_or_404

from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from .models import *
from .form import ReservaForm
from django.views.generic.edit import CreateView,UpdateView,DeleteView
from django.core.urlresolvers import reverse_lazy
# Create your views here.



# clase :crear_reserva
# metodo: post
# template : reserva_form
# post: datos{ ... falta definir modelos}
# request: /reserva_generica/crear_reserva/

def crear_reserva(request, template_name='reserva_generica/reserva_form.html'):
    if request.method == 'POST':
        form = ReservaForm(request.POST)

        if form.is_valid():
            post = form.save(commit=False)
            post.usuario = request.user
            post.save()
            return redirect('reserva_generica:listar_reservas')
        else:
            return redirect('reserva_generica:crear_reserva')
    else:
         form = ReservaForm()
    return render(request, template_name ,{ 'form' : form } )

# class Crear_reserva(CreateView):
#     model = ReservaGenerica
#     fields = ['tipoRecurso','fecha_inicio' , 'fecha_fin']
#     template_name = 'reserva_generica/reserva_form.html'
#     success_url = reverse_lazy('reserva_generica:listar_reservas')



    # reserva = ReservaForm(request.POST or None)
    # if reserva.is_valid():
    #     reserva.save()
    #     return redirect('reserva_generica:listar_reservas')
    # return render(request,template_name,  {'form': reserva})



    # clase: modificar_reserva
    # metodo: get , post
    # template: reserva_form
    # get datos = { ... falta definir modelos}
    # post datos
    # request: /reserva_generica/modificar_reserva/<pk>

class Modificar_reserva(UpdateView):
    model = ReservaGenerica
    fields = ['tipoRecurso','fecha_inicio' , 'fecha_fin']
    template_name = 'reserva_generica/reserva_form.html'
    success_url = reverse_lazy('reserva_generica:listar_reservas')

    # clase : generar_comprobante
    # metodo: get
    # template: comprobante.html
    # get { ... falta definir modelos}
    # request: /reserva_generica/comprobante/<pk>


    # clase: listar_reservas
    # metodo: get
    # template : lista_reservas.html
    # get { ... falta definir modelos}
    # request:  /reserva_generica/lista_de_reservas/
def reserva_list(request, template_name = 'reserva_generica/lista_reservas.html' ):
    reservas = ReservaGenerica.objects.all()
    data = {}
    data['object_list'] = reservas
    return render(request,template_name,data)

    # clase: cancelar_reserva
    # metodo: post
    # template: lista_reservas.html
    # post datos{ ... falta definir modelos }
    # request: /reserva_generica/cancelar_reserva/ ... XXX  falta definir XXX

class Cancelar_reserva(DeleteView):
    model = ReservaGenerica
    fiels = ['tipoRecurso','fecha_inicio' , 'fecha_fin']
    template_name = 'reserva_generica/lista_reservas.html'
    success_url = reverse_lazy('reserva_generica:listar_reservas')

    # clase: solicitud_enviada XXX falta definir XXX sera una clase o una funcion?
    # metodo: no recibe parametros
    # template: solicitud_enviada.html XXX solo seria texto XXX
    # request: /reserva_generica/solucitud_enviada/

castor/reservas/views.py
from django.shortcuts import render

# Create your views here.

castor/reserva_generica/templates/reserva_generica/base.html
{% extends 'common/base.html' %}
{% load staticfiles %}%

castor/reserva_generica/templates/reserva_generica/comprobante.html
<h1>En proceso</h1>

castor/reserva_generica/templates/reserva_generica/lista_reservas.html
{% extends 'common/base.html' %}

{% block title %}{{ reserva_generica }}{% endblock %}
{% block reservas_active %}active{% endblock %}

{% block body %}

<div class="col-lg-12">
    <div class="row">
        <div class="page-header">
            <h1>LISTA DE RESERVAS PENDIENTES</h1>
        </div>
    </div>


    <div class="row"  >
            <div class="panel panel-default">
                <div class="panel-body">
                        <table class="table">
                            <thead>
                            <tr>
                                <th>Usuario</th>
                                <th>Tipo de recurso</th>
                                <th>Fecha inicio</th>
                                <th>Fecha fin</th>

                            </tr>
                            </thead>
                        <tbody>
                            {% for reserva in object_list %}
                                <tr>
                                    <td>{{ reserva.usuario.first_name }} {{ reserva.usuario.last_name }}</td>
                                    <td>{{ reserva.tipoRecurso}}</td>
                                    <td>{{ reserva.fecha_inicio}}</td>
                                    <td>{{ reserva.fecha_fin}}</td>
                                    <td>
                                     <a href="#"0 ->
                                      <button type="submit" class="btn btn-danger btn-xs">
                                      <span class="glyphicon glyphicon-pencil"></span>&nbsp; Modificar reserva
                                      </button>
                                    </a>

                                      <a href="#"0 ->
                                      <button type="submit" class="btn btn-danger btn-xs">
                                      <span class="glyphicon glyphicon-pencil"></span>&nbsp; Cancelar reserva
                                      </button>
                                    </a>

                                    </td>
                                </tr>

                            {% endfor %}
                        </tbody>
                        </table>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

castor/reserva_generica/templates/reserva_generica/reserva_form.html
{% extends 'reserva_generica/base.html' %}
{% block title %}crear nueva solicitud de reserva{% endblock %}
{% block recurso_active %}Activar{% endblock %}




    <head>
        <link rel="stylesheet"
              href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.css">
        <link rel="stylesheet"
              href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-theme.css">
        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.js">
        </script>
        <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.js">
        </script>
        {{ form.media }}
    </head>





{% block body %}
<div class="container-fluid">

    <div class="row">

        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>RESERVAR</h3>
                    {% if error_message %}
                      <p><strong>{{ error_message }}</strong></p>
                    {% endif %}


                    <form class="form-horizontal" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'recursos/form-template.html' %}

                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <a href="{% url 'recursos:recurso_list' %}">
                                <button type="submit"class="btn btn-success">ACEPTAR</button>
                                </a>
                            </div>
                        </div>
                </form>

                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

castor/reserva_generica/templates/reserva_generica/solicitud_enviada.html
<h1>En proceso</h1>