castor/castor/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.auth import views as log_views
from common import views as common
from django.contrib.auth import  views as auth_views



urlpatterns = [
    url(r'^', include('users.urls', namespace='users')),
    url(r'^panel', common.panel),
    url(r'^reservas', common.reservas),
    url(r'^recursos/', include('recursos.urls', namespace='recursos')),
    url(r'^admin/', admin.site.urls),
    url(r'^reserva_generica/', include('reserva_generica.urls',namespace='reserva_generica')),
    url(r'^logout/', log_views.logout,name='logout'),
    url(r'^$', common.start),

    url(r'^password_reset/$', auth_views.password_reset, name='password_reset'),
    url(r'^password_reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm, name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.password_reset_complete, name='password_reset_complete'),
]
urlpatterns += staticfiles_urlpatterns()

castor/recursos/urls.py
from django.conf.urls import  url
from . import views
from .views import *

urlpatterns = [
  url(r'^$', views.IndexView.as_view(), name='index'),
  url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),

  url(r'tiporecurso/add/$', views.CrearTipo.as_view(), name='agregar-tiporecurso'),
  url(r'tiporecurso/(?P<pk>[0-9]+)/$', tiporecurso_update, name='actualizar-tiporecurso'),
  url(r'tiporecurso/(?P<pk>[0-9]+)/eliminar/$', views.EliminarTipo.as_view(), name='eliminar-tiporecurso'),

  url(r'^edit/(?P<pk>\d+)$', recurso_update, name='recurso_edit'),
  url(r'^lista/$', recurso_list, name='recurso_list'),
  url(r'^new/$', recurso_create, name='recurso_new'),
  url(r'^delete/(?P<pk>\d+)$', views.recursoDelete.as_view(), name='recurso_delete'),
  url(r'^tiporecurso/recursos/(?P<pk>\d+)$', views.eliminarRecurso.as_view(), name='eliminar_recurso'),
  url(r'^busqueda/recursos/$', recurso_busqueda , name='recurso_busqueda'),
  url(r'^busqueda/tipo_recurso/$', tipo_recurso_busqueda , name='tipo_recurso_busqueda'),
  url(r'^estados/$', recurso_estados, name='recurso_estados'),


]

castor/users/urls.py
from django.conf.urls import url
from django.contrib.auth import  views as auth_views
from .views import *


urlpatterns = [
    url(r'^login/$', auth_views.login,  {'template_name': 'users/login.html', }),
    url(r'^register/$', register),
    url(r'^users/$', users_list, name='user_list'),

    url(r'^users/pending/$', users_pending, name='user_pending'),
    url(r'^categoria/(?P<pk>\d+)$', categoria, name='usuario_categoria'),
    url(r'^users/roles/(?P<pk>[0-9]+)/$', administrar_rol_user , name='admin_rol'),
    url(r'^users/edit/(?P<pk>\d+)$', users_update, name='users_edit'),
    url(r'^users/approve/(?P<pk>\d+)$', users_approve, name='users_approve'),
    url(r'^users/new/$', users_create, name='users_new'),
    url(r'^users/delete/(?P<pk>\d+)$', users_delete, name='users_delete'),
    url(r'^users/inicio', inicio, name='users_inicio'),

    url(r'^password_reset/$', auth_views.password_reset, name='password_reset'),
    url(r'^password_reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm, name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.password_reset_complete, name='password_reset_complete'),


    url(r'^login/users/inicio/$', inicio,name='users_inicio'),

    url(r'^roles/$', groups_list, name='groups_list'),
    url(r'^roles/new$', groups_create, name='groups_new'),
    url(r'^roles/edit/(?P<pk>\d+)$', groups_update, name='groups_edit'),
    url(r'^roles/delete/(?P<pk>\d+)$', groups_delete, name='groups_delete'),


]

castor/common/views.py
from django.shortcuts import Http404
from . import decorators


def panel(request):
    return Http404()


def reservas(request):
    return Http404()


@decorators.redirect_on_group('admin', '/panel')
@decorators.redirect_on_group('users', '/reservas')
def start(request):
    return Http404()

castor/common/templates/common/nav/header.html
<div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="icon-bar"> </span>
        <span class="icon-bar"> </span>
        <span class="icon-bar"> </span>
    </button>
    <a class="navbar-brand" href="{% url 'recursos:index' %}">INICIO</a>
</div>

castor/common/templates/common/nav/sidenav.html
{% load styled_elements %}
<div class="navbar-default sidebar" role="navigation">
    <div class="sidebar-nav navbar-collapse">


        <ul class="nav" id="side-menu">
            <li>
                <a href="#"><i class="fa fa-user fa-fw"></i>USUARIOS<span class="fa arrow"></span></a>
                {% navbar class="nav-second-level"%}
                    {% navitem 'users:user_list'|as_url "USUARIOS" %}
                    {% navitem 'users:user_pending'|as_url "PENDIENTES DE APROBACION" %}
                {% endnavbar %}
            </li>
            <li>
                <a href="/roles/"><i class="fa fa-group fa-fw"></i>ROLES<span class="fa arrow"></span></a>
            </li>
            <li>
                <a href="#"><i class="fa fa-wrench fa-fw"></i>RECURSOS<span class="fa arrow"></span></a>
                {% navbar class="nav-second-level"%}
                    {% navitem 'recursos:recurso_list'|as_url "RECURSOS" %}
                    {% navitem 'recursos:index'|as_url "TIPOS DE RECURSOS" %}
                {% endnavbar %}
            </li>
            <li>
                <a href="#"><i class="fa fa-amazon fa-fw"></i> RESERVAS<span class="fa arrow"></span></a>
                {% navbar class="nav-second-level"%}
                    {% navitem 'reserva_generica:crear_reserva'|as_url "Reserva generica" %}
                    {% navitem 'recursos:index'|as_url "Reserva especifica" %}
                    {% navitem 'reserva_generica:listar_reservas'|as_url "Lista reservas" %}
                {% endnavbar %}
            </li>

        </ul>
    </div>
        <!-- /.sidebar-collapse -->
</div>
    <!-- /.navbar-static-side -->

castor/common/templates/common/nav/topnav.html
       {% csrf_token %}
{% block extra_heading%}{% endblock%}
<ul class="nav navbar-top-links navbar-right">
    <li class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
            <i class="fa fa-envelope fa-fw"></i> <i class="fa fa-caret-down"></i>
        </a>
        <ul class="dropdown-menu dropdown-messages">
            <li>
                <a href="#">
                    <div>
                        <strong>John Smith</strong>
                        <span class="pull-right text-muted">
                            <em>Yesterday</em>
                        </span>
                    </div>
                    <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eleifend...</div>
                </a>
            </li>
            <li class="divider"></li>
        </ul>
        <!-- /.dropdown-messages -->
    </li>
    <!-- /.dropdown -->
    <li class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
            <i class="fa fa-tasks fa-fw"></i> <i class="fa fa-caret-down"></i>
        </a>
        <ul class="dropdown-menu dropdown-tasks">
            <li>
                <a href="#">
                    <div>
                        <p>
                            <strong>Task 1</strong>
                            <span class="pull-right text-muted">40% Complete</span>
                        </p>
                        <div class="progress progress-striped active">
                            <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: 40%">
                                <span class="sr-only">40% Complete (success)</span>
                            </div>
                        </div>
                    </div>
                </a>
            </li>
        </ul>
        <!-- /.dropdown-tasks -->
    </li>
    <!-- /.dropdown -->
    <li class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
            <i class="fa fa-bell fa-fw"></i> <i class="fa fa-caret-down"></i>
        </a>
        <ul class="dropdown-menu dropdown-alerts">
            <li>
                <a href="#">
                    <div>
                        <i class="fa fa-comment fa-fw"></i> New Comment
                        <span class="pull-right text-muted small">4 minutes ago</span>
                    </div>
                </a>
            </li>
            <li class="divider"></li>
        </ul>
        <!-- /.dropdown-alerts -->
    </li>
    <!-- /.dropdown -->
    <li class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
            <i class="fa fa-user fa-fw"></i> <i class="fa fa-caret-down"></i>
        </a>
        <ul class="dropdown-menu dropdown-user">
            <li><a href="#"><i class="fa fa-user fa-fw"></i> User Profile</a>
            </li>
            <li><a href="#"><i class="fa fa-gear fa-fw"></i> Settings</a>
            </li>
            <li class="divider"></li>
            <li><a href="/logout"><i class="fa fa-sign-out fa-fw"></i> Logout</a>
            </li>
        </ul>
        <!-- /.dropdown-user -->
    </li>
    <!-- /.dropdown -->
</ul>