castor/castor/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.auth import views as log_views
from common import views as common
from django.contrib.auth import  views as auth_views



urlpatterns = [
    url(r'^', include('users.urls', namespace='users')),
    url(r'^panel', common.panel),
    url(r'^reservas', common.reservas),
    url(r'^recursos/', include('recursos.urls', namespace='recursos')),
    url(r'^admin/', admin.site.urls),
    url(r'^reserva_generica/', include('reserva_generica.urls',namespace='reserva_generica')),
    url(r'^logout/', log_views.logout,name='logout'),
    url(r'^$', common.start),

    url(r'^password_reset/$', auth_views.password_reset, name='password_reset'),
    url(r'^password_reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm, name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.password_reset_complete, name='password_reset_complete'),
]
urlpatterns += staticfiles_urlpatterns()

castor/users/urls.py
from django.conf.urls import url
from django.contrib.auth import  views as auth_views
from .views import *


urlpatterns = [
    url(r'^login/$', auth_views.login,  {'template_name': 'users/login.html', }),
    url(r'^register/$', register),
    url(r'^users/$', users_list, name='user_list'),

    url(r'^users/pending/$', users_pending, name='user_pending'),
    url(r'^categoria/(?P<pk>\d+)$', categoria, name='usuario_categoria'),
    url(r'^users/roles/(?P<pk>[0-9]+)/$', administrar_rol_user , name='admin_rol'),
    url(r'^users/edit/(?P<pk>\d+)$', users_update, name='users_edit'),
    url(r'^users/approve/(?P<pk>\d+)$', users_approve, name='users_approve'),
    url(r'^users/new/$', users_create, name='users_new'),
    url(r'^users/delete/(?P<pk>\d+)$', users_delete, name='users_delete'),
    url(r'^users/inicio', inicio, name='users_inicio'),

    url(r'^password_reset/$', auth_views.password_reset, name='password_reset'),
    url(r'^password_reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm, name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.password_reset_complete, name='password_reset_complete'),


    url(r'^login/users/inicio/$', inicio,name='users_inicio'),

    url(r'^roles/$', groups_list, name='groups_list'),
    url(r'^roles/new$', groups_create, name='groups_new'),
    url(r'^roles/edit/(?P<pk>\d+)$', groups_update, name='groups_edit'),
    url(r'^roles/delete/(?P<pk>\d+)$', groups_delete, name='groups_delete'),


]

castor/users/models.py
from django.db import models
from django.contrib.auth.models import User

STATUS_CHOICES = (
    (0,"No asignado"),
    (1, "Titular"),
    (2, "Adjunto"),
    (3, "Asistente"),
    (4, "Encargado"),
    (5, "Auxiliar"),
    (6, "Alumno"),
    (7, "Funcionario"),
)


#**Class Usuario**
"""
Crea la clase usuario con sus atributos
"""
class Usuario(User):
    ci = models.CharField(max_length=20)
    rol = models.IntegerField(null=True)
    categoria = models.IntegerField(choices=STATUS_CHOICES, default=0)
    direccion = models.CharField(max_length=100)
    telefono = models.CharField(max_length=20)

castor/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import Group
from .models import Usuario
from django.core.exceptions import ValidationError, ObjectDoesNotExist
from django_select2.forms import *

#**Class RegisterForm**
"""
Crea la clase de formulario de Registro de usuario con sus atributos
"""
class RegisterForm(UserCreationForm):
    first_name = forms.CharField(label="Nombre")
    last_name = forms.CharField(label="Apellido")
    email = forms.EmailField(label="Correo electronico")
    ci = forms.CharField(max_length=20, label="CI")
    telefono = forms.CharField(max_length=20, label="Telefono")
    direccion = forms.CharField(max_length=100, label="Direccion")

    class Meta:
        model = Usuario
        fields = ("ci", "username", "email", "first_name", "last_name", "telefono", "direccion", "password1",  "password2", )

    def __init__(self, *args, **kwargs):
        super(RegisterForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({'class': 'form-control'})

    # **clean_email**
    """
    Verifica que el correo no este asignado a un usuario ya registrado
    """
    def clean_email(self):
        email = self.cleaned_data["email"]
        try:
            Usuario.objects.get(email=email)
        except ObjectDoesNotExist:
            return email
        raise ValidationError("A user with that email address already exists.")

    # **save**
    """
    guarda el usuario
    """
    def save(self, commit=True):
        user = super(UserCreationForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        user.is_active = False
        if commit:
            user.save()
        return user

#**Class GroupsForm**
"""
Crea la clase de formulario de roles de usuario con sus atributos
"""
class GroupsForm(forms.ModelForm):
    class Meta:
        model = Group
        fields = ['name', 'permissions']
        widgets = {
                'permissions': Select2MultipleWidget
        }
    def __init__(self, *args, **kwargs):
        super(GroupsForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            if self.fields[field].widget.__class__.__name__ != 'CheckboxInput':
                self.fields[field].widget.attrs = {
                    'class': 'form-control'
                }

#**Class UserForm**
"""
Crea la clase de formulario de usuario con sus atributos
"""
class UserForm(forms.ModelForm):
    class Meta:
        model = Usuario
        fields = (
            'ci', 'username', 'first_name', 'last_name', 'email', 'direccion', 'telefono', 'password', 'categoria',
            'is_active',)

    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            if self.fields[field].widget.__class__.__name__ != 'CheckboxInput':
                self.fields[field].widget.attrs = {
                    'class': 'form-control'
                }

castor/users/views.py
from django.shortcuts import render, HttpResponseRedirect, redirect, get_object_or_404
from django.contrib import messages

from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail
from django.conf import settings

from .models import Usuario
from .forms import RegisterForm, GroupsForm, UserForm
from django.contrib.auth.models import Group
from django.forms import ModelForm


#**handle_POST**
"""
Retorna una funcion si el metodo del request es POST
"""
def handle_POST(request, fn):
    if (request.method == 'POST'):
        return fn(request)
    return None

#**handle_POST**
"""
Retorna una funcion si el metodo del request es POST
"""
def handle_GET(request, fn):
    if (request.method == 'GET'):
        return fn(request)
    return None

#**notifyRegister**
"""
Notifica al usuario que su Registro fue exitoso
"""
def notifyRegister(request, email):
    subject = 'Registro sistema reservas'
    message = 'Se ha enviado una solicitud al Administrador.'
    from_email = settings.EMAIL_HOST
    to_list = [email, settings.EMAIL_HOST_USER]

    send_mail(subject, message, from_email, to_list, fail_silently=True)

    messages.success(request, 'SU REGISTRO HA SIDO PROCESADO CON EXITO')
    return

#**register**
"""
Verifica que el registro sea valido. De ser valido, crea el usuario
"""
def register(request):
    form = RegisterForm(request.POST) if request.method == 'POST' else RegisterForm()
    if request.method == 'POST' and form.is_valid():
        save_it=form.save(commit=False)
        save_it.save()


        subject = 'Registro sistema reservas'
        message = 'Su registro ha sido procesado con exito. \n Se ha enviado una solicitud al Administrador.\n Una vez que su solicitud halla sido procesada, se le notificara nuevamente. \n\n Saludos.\n\n El equipo de desarrollo.'
        from_email = settings.EMAIL_HOST
        to_list = [save_it.email, settings.EMAIL_HOST_USER]

        send_mail(subject, message, from_email, to_list, fail_silently=True)
        return HttpResponseRedirect('/login?newuser=true')

    context = {
        'form': form
    }
    return render(request, 'users/register.html', context)

#**search_users**
"""
Busca el usuario solicitado segun el criterio seleccionado
"""
def search_users(request):
    criteria = {}
    field = request.GET.get('field', None)
    if field is None:
        return Usuario.objects.all()
    criteria[field + "__iexact"] = request.GET.get('q', "")
    return Usuario.objects.filter(**criteria)

#**users_list**
"""
lista los usuarios
"""
@login_required(login_url='/login/')
def users_list(request):
    """
    """
    result = {
        'object_list': handle_GET(request, search_users),
    }
    return render(request, 'users/users_list.html', result)

#**asignar_roles**
"""
retorna el id de los roles seleccionados
"""
def asignar_roles(user):
    def __(request):

        get_id = lambda x: int(x.split('-')[-1:][0])
        keys = filter(lambda x: 'user-role' in x,  request.POST.keys())
        valid = [get_id(x) for x in keys]
        return valid
        # valid = [int(x.split('-')[-1:][0]) for x in keys]

    return __

#**administrar_rol_user**
"""
asigna roles a los usuarios
"""
@login_required(login_url='/login/')
def administrar_rol_user(request, pk,template_name='users/rol_admin.html'):
    user = get_object_or_404(Usuario, pk=pk)
    print (user)
    valid=handle_POST(request, asignar_roles(user))
    if valid is not None:
        user.groups.clear()
        for n in valid:
            g = Group.objects.get(pk=n)
            g.user_set.add(user)

        return redirect('/users/')
    lista_roles = Group.objects.all()
    data = {'object_list' : lista_roles, 'user': Usuario, 'user_groups': user.groups.all()}
    return render(request, template_name, data)


#**users_create**
"""
El administrador crea un usuario
"""
@login_required(login_url='/login/')
def users_create(request, template_name='users/user_form.html'):
    form = UserForm(request.POST or None)

    activo = False
    if request.POST.get('is_active') == 'on':
        activo = True

    if form.is_valid():
        Usuario.objects.create_user(
            request.POST['username'],
            email=request.POST['email'],
            password=request.POST['password'],
            first_name=request.POST['first_name'], last_name=request.POST['last_name'],
            ci=request.POST['ci'],
            telefono=request.POST['telefono'], direccion=request.POST['direccion'],
            categoria=request.POST['categoria'],
            is_active=activo
        )

        return redirect('users:user_list')
    return render(request, template_name, {'form': form})

#**users_update**
"""
Modifica los datos del usuario
"""
@login_required(login_url='/login/')
def users_update(request, pk, template_name='users/user_form.html'):
    usuario = get_object_or_404(Usuario, pk=pk)
    print('el usuario es: ', usuario)
    form = UserForm(request.POST or None, instance=usuario)
    if form.is_valid():
        form.save()
        return redirect('/users/')
    return render(request, template_name, {'form': form})

#**users_delete**
"""
Elimina el usuario seleccionado
"""
@login_required(login_url='/login/')
def users_delete(request, pk, template_name='users/user_confirm_delete.html'):
    usuario = get_object_or_404(Usuario, pk=pk)
    if request.method == 'POST':
        usuario.delete()
        return redirect('users:user_list')
    return render(request, template_name, {'object': usuario})

#**groups_list**
"""
lista los roles de usuario
"""
@login_required(login_url='/login/')
def groups_list(request, template_name='users/group_list.html'):
    grupos = Group.objects.all()
    data = {
        'object_list' : grupos
    }
    return render(request, template_name, data)


# TODO: falta cambiarle el nombre a los permisos, y definir que permisos se van a poder seleccionar
#**groups_create**
"""
El administrador crea un rol de usuario
"""
@login_required(login_url='/login/')
def groups_create(request, template_name='users/group_form.html'):
    form = GroupsForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('users:groups_list')
    return render(request, template_name, {'form': form})

#**groups_update**
"""
Modifica los datos del grupo de usuarios
"""
@login_required(login_url='/login/')
def groups_update(request, pk, template_name='users/group_form.html'):
    grupo = get_object_or_404(Group, pk=pk)
    form = GroupsForm(request.POST or None, instance=grupo)
    if form.is_valid():
        form.save()
        return redirect('users:groups_list')
    return render(request, template_name, {'form': form})

#**groups_delete**
"""
Elimina el grupo de usuarios seleccionado
"""
@login_required(login_url='/login/')
def groups_delete(request, pk, template_name='users/group_confirm_delete.html'):
    grupo = get_object_or_404(Group, pk=pk)
    if request.method == 'POST':
        grupo.delete()
        return redirect('users:groups_list')
    return render(request, template_name, {'object': grupo})

#**users_pending**
"""
Genera un listado de los usuarios pendientes de aprobacion
"""
@login_required(login_url='/login/')
def users_pending(request):
    result = {
        'object_list': Usuario.objects.filter(is_active=False),
    }
    return render(request, 'users/users_pending.html', result)


#**users_approve**
"""
Genera un listado de los usuarios aprobados
"""
def users_approve(request):
    result = {
        'object_list': Usuario.objects.filter(is_active=False),
    }
    return render(request, 'users/users_list.html', result)


#**inicio**
"""
Retorna la pagina de inicio
"""
@login_required(login_url='/login/')
def inicio(request):
    return render(request, 'inicio.html')




#**Class UsuarioForm**
"""
Formulario de usuarios y sus categorias
"""
class UsuarioForm(ModelForm):
    class Meta:
        model = Usuario
        fields = ['categoria']

#**categoria**
"""
Asigna una categoria al usuario
"""
def categoria(request, pk, template_name='users/usuario_categoria.html'):
    usuario = get_object_or_404(Usuario, pk=pk)
    form = UsuarioForm(request.POST or None, instance=usuario)
    if form.is_valid():
        if(usuario.categoria!=0):
            print(usuario.email)
            usuario.is_active=True
        form.save()

        subject = 'Bienvenido al sistena de reservas de recursos'
        message = 'Su solicitud ha sido confirmada.\nAhora puede logearse y empezar a utilizar el sistema.\n\nSaludos.\n\nEl equipo de desarrollo, '
        from_email = settings.EMAIL_HOST
        to_list = [usuario.email, settings.EMAIL_HOST_USER]

        send_mail(subject, message, from_email, to_list, fail_silently=True)

        return redirect('users:user_pending')
    return render(request, template_name, {'form':form})

castor/users/templates/users/form-template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

castor/users/templates/users/group_confirm_delete.html
<form method="post">{% csrf_token %}
   ESTAS SEGURO QUE DESEA ELIMINAR EL ROL "{{ object }}" ?
    <input type="submit" value="Submit" />
</form>

castor/users/templates/users/group_form.html
{% extends 'recursos/base.html' %}
{% block title %}AGREGAR NUEVO ROL{% endblock %}
{% block recurso_active %}Activar{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">

        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>AGREGAR NUEVO</h3>
                    {% if error_message %}
                      <p><strong>{{ error_message }}</strong></p>
                    {% endif %}


                    <form class="form-horizontal" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% for field in form %}
                            <div class="form-group">
                                <label class="col-sm-2 control-label"> {{ field.name }}</label>
                                <div class="col-sm-10">
                                    {{ field }}
                                    <span class="help-block m-b-none">{{ field.help_text }}</span>
                                </div>
                            </div>
                        {% endfor %}
                        <div class="line line-dashed b-b line-lg pull-in"></div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <a href="{% url 'users:groups_list' %}">
                                <button type="submit"class="btn btn-success">ACEPTAR</button>
                                </a>
                                <a href="{% url 'users:groups_list' %}">
                                <button type="button" class="btn btn-default">CANCELAR</button>
                                </a>

                            </div>
                            <div class="col-sm-offset-2 col-sm-10">
                            </div>
                        </div>
                </form>

                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

castor/users/templates/users/group_list.html
{% extends 'common/base.html' %}



{% block body %}
<div class="col-lg-12">
    <div class="row">
        <div class="page-header">
            <h1>LISTA DE ROLES</h1>
            <a href="{% url 'users:groups_new' %}">
                <span aria-hidden="true"></span>&nbsp;
                <button type="submit" class="btn btn-primary glyphicon glyphicon-plus">Agregar</button>
            </a>
        </div>
    </div>

    <div class="row"  >
            <div class="panel panel-default">
                <div class="panel-body">
                        <table class="table">
                            <thead>
                            <tr>
                                <th>Nombre</th>
                                <th> </th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for groups in object_list %}
                                <tr>
                                    <td>
                                        <a href={% url 'users:groups_edit' groups.id %}> {{ groups.name}}</a>
                                    </td>
                                    <td>
                                        <a href="{% url 'users:groups_delete' pk=groups.id %}">
                                        <button type="submit" class="btn btn-default btn-sm" >
                                            <span class=" btn-default glyphicon glyphicon-trash"></span>&nbsp
                                        </button></a>
                                    </td>
                                </tr>

                            {% endfor %}
                        </tbody>
                        </table>

                </div>
            </div>
      </div>
</div>
{% endblock %}

castor/users/templates/users/login.html
{% load static  %}

<!-- All the files that are required -->
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'aether.css' %}">

<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
<link href='http://fonts.googleapis.com/css?family=Varela+Round' rel='stylesheet' type='text/css'>

<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />

<!-- Where all the magic happens -->
<!-- LOGIN FORM -->
<body>
<div class="text-center" style="padding:50px 0">
    <div class="logo">login</div>
    <!-- Main Form -->
    <div class="login-form-1">
        <form id="login-form" class="text-left" method="post"> {% csrf_token %}
            <div class="login-form-main-message"></div>
            <div class="main-login-form">
                <div class="login-group">
                    <div class="form-group">
                        {{form.username.errors}}
                        {{form.username.label_tag}}
                        {{form.username}}
                    </div>
                    <div class="form-group">
                        {{form.password.errors}}
                        {{form.password.label_tag}}
                        {{form.password}}
                    </div>
                </div>

                <button type="submit" class="login-button"><i class="fa fa-chevron-right"></i></button>
            </div>
            <div class="etc-login-form">
                {{form.non_field_errors}}
                <p>no recuerda su password? <a href="../password_reset">click aqui</a></p>
                <p>nuevo usuario? <a href="../register">crear nueva cuenta</a></p>
            </div>
        </form>
    </div>
    <!-- end:Main Form -->
</div>

<script src="{% static 'js/jquery.min.js' %}" ></script>
<script src="{% static 'js/bootstrap.min.js' %}" ></script>
<script src="{% static 'aether.js' %}" ></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.13.1/jquery.validate.min.js"></script>
</body>

castor/users/templates/users/user_confirm_delete.html
<form method="post">{% csrf_token %}
   ESTAS SEGURO QUE DESEA ELIMINAR AL USUARIO "{{ object }}" ?
    <input type="submit" value="Submit" />
</form>

castor/users/templates/users/users_list.html
{% extends 'common/base.html' %}

{% block search_form %}
<form class="navbar-form navbar-left" role="search" method="get">
    <div class="form-group">
        <label for="username">Valor</label>
        <input type="text" class="form-control" value="" name="q">
    </div>
    <div class="form-group">
        <label for="field">Filtro</label>
        <select class="form-group select" name="field">
            <option value="first_name">Nombre</option>
            <option value="last_name">Apellido</option>
            <option value="username">Nombre de Usuario</option>
            <option value="ci">Cedula de Identidad</option>
            <option value="email">Email</option>
        </select>
    </div>
<button type="submit" class="btn btn-default">Buscar Usuario</button>
</form>
{% endblock %}

{% block body %}
<div class="col-lg-12">
    <div class="row">
        <div class="page-header">
            <h1>LISTA DE USUARIOS</h1>
            <a href="{% url 'users:users_new' %}">
                <span aria-hidden="true"></span>&nbsp;
                <button type="submit" class="btn btn-primary glyphicon glyphicon-plus">Agregar Usuario</button>
            </a>
        </div>
    </div>

    <div class="row"  >
            <div class="panel panel-default">
                <div class="panel-body">
                        <table class="table">
                            <thead>
                            <tr>
                                <th>Cedula</th>
                                <th>Nombres y Apellidos</th>
                                <th>Email</th>
                                <th>Username</th>
                                <th>Categoria</th>
                                <th>Status</th>
                                <th> </th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for users in object_list %}
                                <tr>
                                    <td>{{ users.ci }}</td>

                                    <td>
                                        <a href="{% url 'users:users_edit' users.id %}" >
                                        {{ users.first_name}} {{ users.last_name }}
                                        </a>
                                    </td>
                                    <td>{{ users.email }}</td>
                                    <td>{{ users.username  }}</td>
                                    <td>{{ users.get_categoria_display }}</td>
                                    <td class="text-center">
                                        <a href class="active" ui-toggle-class>
                                            {% if users.is_active %}
                                                <a href class="active"><i class="fa fa-check text-success text-active"></i></a>
                                            {% else %}
                                                <a href class=""><i class="fa fa-times text-danger text"></i></a>
                                            {% endif %}
                                        </a>
                                    </td>
                                    <td>

                                        <a href="{% url 'users:admin_rol' pk=users.id %}">
                                        <button type="submit" class="btn btn-default btn-sm" >
                                            <span class="glyphicon glyphicon-plus"></span>&nbsp;Rol
                                        </button></a>
                                        <a href="{% url 'users:users_delete' pk=users.id %}">
                                        <button type="submit" class="btn btn-default btn-sm" >
                                            <span class=" btn-default glyphicon glyphicon-trash"></span>&nbsp
                                        </button></a>
                                    </td>
                                </tr>

                            {% endfor %}
                        </tbody>
                        </table>

                </div>
            </div>
      </div>
</div>
{% endblock %}

castor/users/templates/users/users_pending.html
{% extends 'common/base.html' %}

{% block search_form %}
<form class="navbar-form navbar-left" role="search" method="get">
    <div class="form-group">
        <label for="username">Valor</label>
        <input type="text" class="form-control" value="" name="q">
    </div>
    <div class="form-group">
        <label for="field">Filtro</label>
        <select class="form-group select" name="field">
            <option value="first_name">Nombre</option>
            <option value="last_name">Apellido</option>
            <option value="username">Nombre de Usuario</option>
            <option value="ci">Cedula de Identidad</option>
            <option value="email">Email</option>
        </select>
    </div>
<button type="submit" class="btn btn-default">BuscarUsuario</button>
</form>
{% endblock %}

{% block body %}
<div class="col-lg-12">
    <div class="row">
        <div class="page-header">
            <h1>LISTA DE USUARIOS PENDIENTES</h1>
        </div>
    </div>

    <div class="row"  >
            <div class="panel panel-default">
                <div class="panel-body">
                        <table class="table">
                            <thead>
                            <tr>
                                <th>Cedula</th>
                                <th>Nombres y Apellidos</th>
                                <th>Email</th>
                                <th>Username</th>
                                <th>Categoria</th>
                                <th>Status</th>
                                <th> </th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for users in object_list %}
                                <tr>
                                    <td>{{ users.ci }}</td>

                                    <td>
                                        <a href="{% url 'users:users_edit' users.id %}" >
                                        {{ users.first_name}} {{ users.last_name }}
                                        </a>
                                    </td>
                                    <td>{{ users.email }}</td>
                                    <td>{{ users.username  }}</td>
                                    <td>{{ users.get_categoria_display }}</td>
                                    <td class="text-center">
                                        <a href class="active" ui-toggle-class>
                                            {% if usuario.is_active %}
                                                <a href class="active"><i class="fa fa-check text-success text-active"></i></a>
                                            {% else %}
                                                <a href class=""><i class="fa fa-times text-danger text"></i></a>
                                            {% endif %}
                                        </a>
                                    </td>
                                    <td>

                                        <a href="{% url 'users:usuario_categoria' users.id %}" class="btn btn-default btn-sm" role="button">
                                        <button type="submit" class="btn btn-default btn-sm" >
                                            <span class="glyphicon glyphicon-user"></span>&nbsp;Asignar categoria
                                        </button></a>

                                        {#  <a href="#">#}
                                        {# <button type="submit" class="btn btn-default btn-sm" > #}
                                          {#  <span class="glyphicon glyphicon-ok"></span>&nbsp;Aceptar #}
                                       {# </button></a> #}

                                    </td>
                                </tr>

                            {% endfor %}
                        </tbody>
                        </table>

                </div>
            </div>
      </div>
</div>
{% endblock %}

castor/users/templates/users/usuario_categoria.html
{% extends 'common/base.html' %}
{% block title %}AGREGAR CATEGORIA{% endblock %}
{% block recurso_active %}Activar{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">

        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Agregar categoria a usuario</h3>
                    {% if error_message %}
                      <p><strong>{{ error_message }}</strong></p>
                    {% endif %}


                    <form class="form-horizontal" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'users/form-template.html' %}

                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <a href="{% url 'users:user_pending' %}">
                                <button type="submit"class="btn btn-success">ACEPTAR</button>
                                </a>
                            </div>
                        </div>
                </form>

                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}