castor/castor/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.auth import views as log_views
from common import views as common
from django.contrib.auth import  views as auth_views



urlpatterns = [
    url(r'^', include('users.urls', namespace='users')),
    url(r'^panel', common.panel),
    url(r'^reservas', common.reservas),
    url(r'^recursos/', include('recursos.urls', namespace='recursos')),
    url(r'^admin/', admin.site.urls),
    url(r'^reserva_generica/', include('reserva_generica.urls',namespace='reserva_generica')),
    url(r'^logout/', log_views.logout,name='logout'),
    url(r'^$', common.start),

    url(r'^password_reset/$', auth_views.password_reset, name='password_reset'),
    url(r'^password_reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm, name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.password_reset_complete, name='password_reset_complete'),
]
urlpatterns += staticfiles_urlpatterns()

castor/recursos/urls.py
from django.conf.urls import  url
from . import views
from .views import *

urlpatterns = [
  url(r'^$', views.IndexView.as_view(), name='index'),
  url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),

  url(r'tiporecurso/add/$', views.CrearTipo.as_view(), name='agregar-tiporecurso'),
  url(r'tiporecurso/(?P<pk>[0-9]+)/$', tiporecurso_update, name='actualizar-tiporecurso'),
  url(r'tiporecurso/(?P<pk>[0-9]+)/eliminar/$', views.EliminarTipo.as_view(), name='eliminar-tiporecurso'),

  url(r'^edit/(?P<pk>\d+)$', recurso_update, name='recurso_edit'),
  url(r'^lista/$', recurso_list, name='recurso_list'),
  url(r'^new/$', recurso_create, name='recurso_new'),
  url(r'^delete/(?P<pk>\d+)$', views.recursoDelete.as_view(), name='recurso_delete'),
  url(r'^tiporecurso/recursos/(?P<pk>\d+)$', views.eliminarRecurso.as_view(), name='eliminar_recurso'),
  url(r'^busqueda/recursos/$', recurso_busqueda , name='recurso_busqueda'),
  url(r'^busqueda/tipo_recurso/$', tipo_recurso_busqueda , name='tipo_recurso_busqueda'),
  url(r'^estados/$', recurso_estados, name='recurso_estados'),


]

castor/users/urls.py
from django.conf.urls import url
from django.contrib.auth import  views as auth_views
from .views import *


urlpatterns = [
    url(r'^login/$', auth_views.login,  {'template_name': 'users/login.html', }),
    url(r'^register/$', register),
    url(r'^users/$', users_list, name='user_list'),

    url(r'^users/pending/$', users_pending, name='user_pending'),
    url(r'^categoria/(?P<pk>\d+)$', categoria, name='usuario_categoria'),
    url(r'^users/roles/(?P<pk>[0-9]+)/$', administrar_rol_user , name='admin_rol'),
    url(r'^users/edit/(?P<pk>\d+)$', users_update, name='users_edit'),
    url(r'^users/approve/(?P<pk>\d+)$', users_approve, name='users_approve'),
    url(r'^users/new/$', users_create, name='users_new'),
    url(r'^users/delete/(?P<pk>\d+)$', users_delete, name='users_delete'),
    url(r'^users/inicio', inicio, name='users_inicio'),

    url(r'^password_reset/$', auth_views.password_reset, name='password_reset'),
    url(r'^password_reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm, name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.password_reset_complete, name='password_reset_complete'),


    url(r'^login/users/inicio/$', inicio,name='users_inicio'),

    url(r'^roles/$', groups_list, name='groups_list'),
    url(r'^roles/new$', groups_create, name='groups_new'),
    url(r'^roles/edit/(?P<pk>\d+)$', groups_update, name='groups_edit'),
    url(r'^roles/delete/(?P<pk>\d+)$', groups_delete, name='groups_delete'),


]

castor/recursos/models.py
from django.core.urlresolvers import reverse
from django.db import models
import datetime
from django.utils.timezone import now

STATUS_CHOICES = (
    (1, "Disponible"),
    (2, "Reservado"),
    (3, "Mantenimiento"),
    (4, "Inhabilitado"),
)

#**Class TipoRecurso**
"""
Crea la clase TipoRecurso con sus atributos
"""
class TipoRecurso(models.Model):
    Nombre = models.CharField(max_length=100)
    caracteristicas = models.CharField(max_length=1000)

    # **get_absolute_url**
    """
    retorna el id del recurso, dentro de la URL
    """
    def get_absolute_url(self):
        return reverse('recursos:detail', kwargs={'pk': self.pk})

    # **__str__**
    """
    retorna el nombre del recurso
    """
    def __str__(self):
        return self.Nombre

#**setDisponibles**
"""
retorna la cantidad disponible de recursos
"""
def setDisponibles(self):
    return self.cantidadHabilitada

#**Class Recurso**
"""
Crea la Clase recurso con sus atributos
"""
class Recurso(models.Model):
    tipo = models.ForeignKey(TipoRecurso, on_delete=models.CASCADE)
    nombre = models.CharField(max_length=50)
    estado = models.IntegerField(choices=STATUS_CHOICES, default=1)
    cantidadHabilitada = models.PositiveIntegerField(null=True)
    cantidadReservada = models.PositiveIntegerField(default=0)
    cantidadDisponible = models.PositiveIntegerField(null=True)
    fecha_creacion = models.DateField(default=now)
    TiempoEstimadoVida = models.PositiveIntegerField(default=100)

    # TODO: agregar una funcion on save, para setear el valor de cantidadDisponible

    def __str__(self):
        return self.nombre

    def save(self, *args, **kwargs):
        if not self.cantidadDisponible:
            self.cantidadDisponible = self.cantidadHabilitada
            super(Recurso, self).save(*args, **kwargs)

castor/recursos/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from django.forms import ModelForm
from django.views import generic
from django.views.generic.edit import CreateView,UpdateView,DeleteView
from django.core.urlresolvers import reverse_lazy
from .models import TipoRecurso,Recurso

#**handle_POST**
"""
retorna una funcion, si el metodo del request es POST
"""
def handle_POST(request, fn):
    if (request.method == 'POST'):
        return fn(request)
    return None

#**handle_GET**
"""
retorna una funcion, si el metodo del request es POST
"""
def handle_GET(request, fn):
    if (request.method == 'GET'):
        return fn(request)
    return None


class IndexView(generic.ListView):
    template_name = 'recursos/index.html'
    context_object_name = 'lista'

    #**get_queryset**
    """
    Lista tipo de recursos existentes
    """
    def get_queryset(self):
        return TipoRecurso.objects.all()




#**Class DetailView**
"""
Agrega soporte para comparar con el signo ==
"""
class DetailView(generic.DetailView):
    model = TipoRecurso
    template_name = 'recursos/detalle.html'

#**Class CrearTipo**
"""
Crea un tipo de recurso con sus caracteristicas
"""
class CrearTipo(CreateView):
    model = TipoRecurso
    fields = ['Nombre','caracteristicas']

#**Class ModificarTipo**
"""
Modifica tipo de Recurso
"""
class ModificarTipo(UpdateView):
    model = TipoRecurso
    fields = ['Nombre','caracteristicas']

#**Class TipoRecursoForm**
"""
Crea el formulario utilizado en TipoRecurso
"""
class TipoRecursoForm(ModelForm):
    class Meta:
        model = TipoRecurso
        fields = ['Nombre', 'caracteristicas']


#**tiporecurso_update**
"""
guarda las modificaciones del TipoRecurso seleccionado
"""
def tiporecurso_update(request, pk, template_name='recursos/tiporecurso_form.html'):
    Tiporecurso = get_object_or_404(TipoRecurso, pk=pk)
    form = TipoRecursoForm(request.POST or None, instance=Tiporecurso)
    if form.is_valid():
        form.save()
        print(form.instance)
        return redirect('recursos:index')
    return render(request, template_name, {'form':form})

#**EliminarTipo**
"""
Elimina el TipoRecurso seleccionado
"""
class EliminarTipo(DeleteView):
    model = TipoRecurso
    fields = ['Nombre','caracteristicas']
    success_url = reverse_lazy('recursos:index')

#**Class RecursoForm**
"""
Crea la clase Recurso
"""
class RecursoForm(ModelForm):
    class Meta:
        model = Recurso
        fields = ['tipo', 'nombre', 'estado', 'cantidadHabilitada', 'TiempoEstimadoVida']

#**recurso_list**
"""
Lista los recursos existentes
"""

def recurso_list(request):
    """
    """
    result = {
        'object_list': handle_GET(request, search_recursos),

    }
    return render(request, 'recursos/recurso_list.html' , result)

#**recurso_create**
"""
Crea recurso y le asigna un tipo de recurso
"""
@login_required(login_url='/login/')
def recurso_create(request, template_name='recursos/recurso_form.html'):
    form = RecursoForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect(form.instance.tipo)
    return render(request, template_name, {'form': form})

#**recurso_update**
"""
modifica el recurso seleccionado
"""
@login_required(login_url='/login/')
def recurso_update(request, pk, template_name='recursos/recurso_form.html'):
    recurso = get_object_or_404(Recurso, pk=pk)
    form = RecursoForm(request.POST or None, instance=recurso)
    if form.is_valid():
        form.save()
        print(form.instance)
        return redirect('recursos:recurso_list')
    return render(request, template_name, {'form':form})

#**Class recursoDelete**
"""
Elimina el Recurso seleccionado y direcciona al listado de recursos
"""
class recursoDelete(DeleteView):
    model = Recurso
    fields = ['tipo', 'nombre', 'estado', 'cantidadHabilitada', 'cantidadHabilitada', 'cantidadDisponible',
              'TiempoEstimadoVida']
    success_url = reverse_lazy('recursos:recurso_list')

#**Class eliminarRecurso**
"""
Elimina el Recurso seleccionado y direcciona a la pagina index
"""
class eliminarRecurso(DeleteView):
    model = Recurso
    fields = ['tipo', 'nombre', 'estado', 'cantidadHabilitada', 'cantidadHabilitada', 'cantidadDisponible',
              'TiempoEstimadoVida']
    success_url = reverse_lazy('recursos:index')

#**recurso_busqueda**
"""
Realiza una busqueda del recurso solicitado
"""
@login_required(login_url='/login/')
def recurso_busqueda(request, template_name='recursos/mostrar_recurso_list.html'):

    miNombre = request.GET['q']
    recursos = Recurso.objects.all().filter(nombre=miNombre)
    data = {}
    data['object_list'] = recursos
    return render(request, template_name, data)

#**tipo_recurso_busqueda**
"""
Buscamos todos los recursos que en el campo nombre sean iguales al nombre dado y los listamos
"""
def tipo_recurso_busqueda(request, template_name='recursos/mostrar_tipo_recurso_list.html'):
    print(request.GET  )
    miNombre = request.GET['q']
    print(miNombre)
    tipo_recurso = TipoRecurso.objects.all().filter(Nombre=miNombre)
    data = {}
    if request.GET['q']  is None :
        tipo_recurso = TipoRecurso.objects.all()
    data['object_list'] = tipo_recurso
    return render(request, template_name, data)

#**recurso_estados**
"""
Genera el estado de todos los recursos
"""
@login_required(login_url='/login/')
def recurso_estados(request, template_name='recursos/recurso_estados.html'):
    recurso = Recurso.objects.all()
    data = {}
    data['object_list'] = recurso
    return render(request, template_name, data)

#**search_recursos**
"""
busqueda del recurso solicitado segun el campo seleccionado
"""
@login_required(login_url='/login/')
def search_recursos(request):
    criteria = {}
    field=request.GET.get('field', None)
    if field is None:
        return Recurso.objects.all()
    criteria[field+"__iexact"] = request.GET.get('q', "")
    return Recurso.objects.filter(**criteria)

#**search_TipoRecurso**
"""
busqueda del TipoRecurso solicitado segun el campo seleccionado
"""
@login_required(login_url='/login/')
def search_TipoRecurso(request):
    criteria = {}
    field=request.GET.get('field', None)
    if field is None:
        return TipoRecurso.objects.all()
    criteria[field+"__iexact"] = request.GET.get('q', "")
    return TipoRecurso.objects.filter(**criteria)

castor/recursos/templates/recursos/base.html
{% extends 'common/base.html' %}
{% load staticfiles %}%

castor/recursos/templates/recursos/detalle.html
{% extends 'recursos/base.html' %}
{% block title %}{{ tiporecurso }}{% endblock %}
{% block tiporecursos_active %}active{% endblock %}

{% block search_form %}

<form action="{% url 'recursos:recurso_busqueda'  %}" class="navbar-form navbar-left" role="search" method="get">
    <div   class="form-group">
        <input class="form-control" value=""  id="q" name="q" type="text">
    </div>
    <button type="submit" class="btn btn-default">Busqueda de recurso</button>
</form>

{% endblock %}





{% block body %}


<div class="container-fluid songs-container">

    <div class="row">

        <!-- tiporecurso info-->
        <div class="col-sm-4 col-md-3">
            <div class="panel panel-default">
                <div class="panel-body">
                    <a href="{% url 'recursos:detail' tiporecurso.id %}">

                    </a>
                    <h1>{{ tiporecurso.Nombre }}</h1>
                    <h2>{{ tiporecurso.caracteristicas }}</h2>
                </div>
            </div>
        </div>


        <div class="col-sm-8 col-md-9">

            <ul class="nav nav-pills" style="margin-bottom: 10px;">
                <li role="presentation" class="active"><a href="{% url 'recursos:detail' tiporecurso.id %}">Ver todos</a></li>
                <li role="presentation">
                    <a href="{% url 'recursos:recurso_new' %}">
                    <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp;
                    <button type="submit" class="btn btn-primary">Agregar nuevo recurso</button></a></li>
            </ul>

            <div class="panel panel-default">
                <div class="panel-body">

                    <h3>TODOS LOS RECURSOS</h3>

                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}

                    <table class="table">
                        <thead>
                        <tr>
                            <th>Nombre</th>
                            <th>cantidad Habilitado</th>
                            <th>cantidad Reservado</th>
                            <th>cantidad Disponible</th>
                            <th>Tiempo estimado de vida (años)</th>
                            <th>estado</th>

                        </tr>
                        </thead>
                        <body>
                        {% for recurso in tiporecurso.recurso_set.all %}
                            <tr>
                                <td>{{ recurso.nombre }}</td>
                                <td>{{ recurso.cantidadHabilitada}}</td>
                                <td>{{ recurso.cantidadReservada }}</td>
                                <td>{{ recurso.cantidadDisponible }}</td>
                                <td>{{ recurso.TiempoEstimadoVida }}</td>
                                <td>{{ recurso.get_estado_display}}</td>
                                <td>
                                    <form action="{% url 'recursos:eliminar_recurso' recurso.id %}" method="post" style="display: inline;">
                                        {% csrf_token %}
                                        <input type="hidden" name="recurso_id" value="{{ recurso.id }}" />
                                        <button type="submit" class="btn btn-default btn-sm" onclick="return confirm('SEGURO QUE DESEA ELIMINAR EL RECURSO?')">
                                            <span class="glyphicon glyphicon-remove"></span>&nbsp; Eliminar
                                        </button>
                                    </form>
                                </td>

                                <td>
                                   <a href="{% url 'recursos:recurso_edit' recurso.id %}" class="btn btn-default btn-sm" role="button">
                                        {% csrf_token %}
                                        <input type="hidden" name="recurso_id" value="{{ recurso.id }}" />
                                        <button type="submit" class="btn btn-danger btn-xs">
                                            <span class="glyphicon glyphicon-pencil"></span>&nbsp; Editar
                                        </button>
                                   </a>
                                    </form>
                                </td>
                            </tr>
                        {% endfor %}
                        </body>
                    </table>

                </div>
            </div>

        </div>

    </div>

</div>

{% endblock %}

castor/recursos/templates/recursos/form-template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

castor/recursos/templates/recursos/index.html
{% extends 'recursos/base.html' %}
{#{% block recursos_active %}active{% endblock %}#}


{% block search_form %}

<form action="{% url 'recursos:tipo_recurso_busqueda'  %}" class="navbar-form navbar-left" role="search" method="get">
    <div   class="form-group">
        <input class="form-control" value=""  id="q" name="q" type="text">
    </div>
    <button type="submit" class="btn btn-default">Busqueda de tipo recurso</button>
</form>

{% endblock %}


{% block body %}

<div class="tiporecursos-container container-fluid">



    <div class="row">


{#        {% if lista %}#}
            {% for tiporecurso in lista %}
                <div class="col-sm-8 col-lg-8">
                    <div class="thumbnail">
                        <a href="{% url 'recursos:detail' tiporecurso.id %}">

                        </a>
                        <div class="caption">
                            <h2>{{ tiporecurso.Nombre }}</h2>
                            <h4>{{ tiporecurso.caracteristicas }}</h4>

                            <!-- ver detalles -->
                            <a href="{% url 'recursos:detail' tiporecurso.id %}" class="btn btn-primary btn-sm" role="button">Ver Detalles</a>
                            <a href="{% url 'recursos:actualizar-tiporecurso' tiporecurso.id %}" class="btn btn-default btn-sm" role="button">
                                Editar
                                <span class="glyphicon glyphicon-pencil"/></span>
                            </a>


                            <!-- Eliminar tipo de recurso -->
                            <form action="{% url 'recursos:eliminar-tiporecurso' tiporecurso.id %}" method="post" style="display: inline;">
                                {% csrf_token %}
                                <input type="hidden" name="tiporecurso_id" value="{{ tiporecurso.id }}" />
                                <button type="submit" class="btn btn-default btn-sm" onclick="return confirm('SEGURO QUE DESEA ELIMINAR EL TIPO DE RECURSO?')">
                                    Eliminar<span class="glyphicon glyphicon-trash"/></span>


                                </button>
                            </form>


                        </div>
                    </div>
                </div>

            {% endfor %}
{#        {% else %}#}
            <div class="col-sm-12">
                <br>



                        <a href="{% url 'recursos:agregar-tiporecurso' %}">
                            <button type="button" class="btn btn-success">
                                <span class="glyphicon glyphicon-plus"></span>&nbsp; Agregar un tipo de recurso
                            </button>
                        </a>
            </div>
{#        {% endif %}#}
    </div>

    <!-- busqueda de recursos-->
    {% if recursos %}
        <div class="row">
            <div class="col-sm-12">
                <h3>Recursos</h3>
            </div>
            <div class="col-sm-12">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>NOMBRE</th>
                                    <th>CANTIDAD DISPONIBLE</th>
                                    <th>ESTADO</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for recurso in recurso %}
                                    <tr>
                                        <td>{{ recurso.nombre }}</td>
                                        <td>{{ recurso.tiporecurso.Nombre }}</td>
                                        <td>
                                            <a target="_blank" href="{{ recurso.cantidad}">

                                            </a>
                                        </td>
                                        <td>
                                            <a href="{% url 'recursos:detail' recurso.tiporecurso.id %}">

                                            </a>
                                            <a href="{% url 'recursos:detail' recurso.tiporecurso.id %}">{{ recurso.tiporecurso.Nombre }}</a>
                                        </td>

                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}

</div>
{% endblock %}

castor/recursos/templates/recursos/mostrar_tipo_recurso_list.html
{% extends 'recursos/base.html' %}

{% block title %}{{ recurso }}{% endblock %}
{% block recursos_active %}active{% endblock %}

{% block search_form %}

<form action="{% url 'recursos:tipo_recurso_busqueda'  %}" class="navbar-form navbar-left" role="search" method="get">
    <div   class="form-group">
        <input class="form-control" value=""  id="q" name="q" type="text">
    </div>
    <button type="submit" class="btn btn-default">Busqueda de tipo recurso</button>
</form>

{% endblock %}


{% block body %}

<div class="row" xmlns="http://www.w3.org/1999/html">

        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">


                    <h1>LISTA DE TIPOS DE RECURSOS</h1>
                    <table class="table">
                        <thead>

                        <tr>
                            <th><strong>Nombre     </strong>  </th>
                            <th><strong> Caracteristicas </strong>  </th>
                        </tr>
                        </thead>
                        {% for tipo_recurso in object_list %}
                        <tr>
                            <th>{{ tipo_recurso.Nombre }}</th>
                            <th>{{ tipo_recurso.caracteristicas}}</th>
                        </tr>
                    {% endfor %}
                    </table>




                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

castor/recursos/templates/recursos/recurso_confirm_delete.html
<form method="post">{% csrf_token %}
   ESTAS SEGURO QUE DESEA ELIMINAR EL RECURSO "{{ object }}" ?
    <input type="submit" value="Submit" />
</form>

castor/recursos/templates/recursos/recurso_estados.html
{% extends 'recursos/base.html' %}

{% block title %}{{ recurso }}{% endblock %}
{% block recursos_active %}active{% endblock %}

{% block body %}

<div class="col-lg-12">
    <div class="row">
        <div class="page-header">
            <h1>LISTA RECURSOS</h1>
        </div>
    </div>


    <div class="row"  >
            <div class="panel panel-default">
                <div class="panel-body">
                        <table class="table">
                            <thead>
                            <tr>
                                <th>Nombre Recurso</th>
                                <th>Tipo de recurso</th>
                                <th>Estado</th>

                            </tr>
                            </thead>
                        <tbody>
                            {% for recurso in object_list %}
                                <tr>
                                    <td>{{ recurso.nombre }}</td>
                                    <td>{{ recurso.tipo}}</td>
                                    <td>{{ recurso.get_estado_display}}</td>
                                    <td>
                                     <a href="#"0 ->
                                      <button type="submit" class="btn btn-danger btn-xs">
                                      <span class="glyphicon glyphicon-pencil"></span>&nbsp; Gestionar reserva
                                      </button>
                                    </a>
                                    </td>
                                </tr>

                            {% endfor %}
                        </tbody>
                        </table>




                </div>
            </div>
        </div>
    </div>

{% endblock %}

castor/recursos/templates/recursos/recurso_form.html
{% extends 'recursos/base.html' %}
{% block title %}AGREGAR NUEVO RECURSO{% endblock %}
{% block recurso_active %}Activar{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">

        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>AGREGAR NUEVO</h3>
                    {% if error_message %}
                      <p><strong>{{ error_message }}</strong></p>
                    {% endif %}


                    <form class="form-horizontal" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'recursos/form-template.html' %}

                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <a href="{% url 'recursos:recurso_list' %}">
                                <button type="submit"class="btn btn-success">ACEPTAR</button>
                                </a>
                            </div>
                        </div>
                </form>

                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

castor/recursos/templates/recursos/recurso_list.html
{% extends 'recursos/base.html' %}

{% block search_form %}
<form class="navbar-form navbar-left" role="search" method="get">
    <div class="form-group">
        <label for="recursoname">Valor</label>
        <input type="text" class="form-control" value="" name="q">
    </div>
    <div class="form-group">
        <label for="field">Filtro</label>
        <select class="form-group select" name="field">
            <option value="tipo__Nombre">Tipo</option>
            <option value="nombre">Nombre</option>
        </select>
    </div>
<button type="submit" class="btn btn-default">Buscar Recurso</button>
</form>
{% endblock %}



{% block body %}

<div class="col-lg-12">
    <div class="row">
        <div class="page-header">
            <h1>LISTA RECURSOS</h1>
        </div>
    </div>


    <div class="row"  >
            <div class="panel panel-default">
                <div class="panel-body">
                        <table class="table">
                            <thead>
                            <tr>
                                <th>Nombre Recurso</th>
                                <th>Tipo</th>
                                <th>Estado</th>
                                <th>Cantidad Habilitada</th>
                                <th>Cantidad Reservada</th>
                                <th>Cantidad Disponible</th>
                            </tr>
                            </thead>
                        <tbody>
                            {% for recurso in object_list %}
                                <tr>
                                    <td>{{ recurso.nombre }}</td>
                                    <td>{{ recurso.tipo}}</td>
                                    <td>{{ recurso.get_estado_display}}</td>
                                    <td>{{ recurso.cantidadHabilitada }}</td>
                                    <td>{{ recurso.cantidadReservada}}</td>
                                    <td>{{ recurso.cantidadDisponible}}</td>
                                    <td>
                                     <a href="{% url 'recursos:recurso_edit' recurso.id %}">
                                      <button type="submit" class="btn btn-danger btn-xs">
                                      <span class="glyphicon glyphicon-pencil"></span>&nbsp; Editar
                                      </button>
                                    </a>
                                    <a href="{% url 'recursos:recurso_delete' recurso.id %}">
                                      <button type="submit" class="btn btn-default btn-sm" onclick="return confirm('SEGURO QUE DESEA ELIMINAR EL RECURSO?')">
                                      <span class="glyphicon glyphicon-remove"></span>&nbsp; Eliminar
                                      </button>
                                    </a>
                                    </td>
                                </tr>

                            {% endfor %}
                        </tbody>
                        </table>

       <a href="{% url 'recursos:recurso_new' %}">Agregar nuevo recurso.</a>



                </div>
            </div>
        </div>
    </div>

{% endblock %}

castor/recursos/templates/recursos/tiporecurso_form.html
{% extends 'recursos/base.html' %}
{% block title %}AGREGAR NUEVO TIPO DE RECURSO{% endblock %}
{% block tiporecurso_active %}Activar{% endblock %}

{% block search_form %}

<form action="{% url 'recursos:tipo_recurso_busqueda'  %}" class="navbar-form navbar-left" role="search" method="get">
    <div   class="form-group">
        <input class="form-control" value=""  id="q" name="q" type="text">
    </div>
    <button type="submit" class="btn btn-default">Busqueda de tipo recurso</button>
</form>

{% endblock %}


{% block body %}
<div class="container-fluid">

    <div class="row">

        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>AGREGAR NUEVO</h3>
                    {% if error_message %}
                      <p><strong>{{ error_message }}</strong></p>
                    {% endif %}


                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'recursos/form-template.html' %}

                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit"class="btn btn-success">ACEPTAR</button>
                            </div>
                        </div>
                </form>

                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}